apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      affinity:
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms:
              - matchExpressions:
                - key: app 
                  operator: In 
                  values: 
                  - infra
      containers:
      - name: myapp2
        image: busybox
        resources:
          requests:
            cpu: "300m"
            memory: "200Mi"
          limits:
            memory: "600Mi"
            cpu: "500m"
        command:
          - sleep
          - "3600"