apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      affinity: 
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: app 
                operator: In 
                values: 
                - mgmt
      containers:
      - name: myapp1
        image: busybox
        resources:
          requests:
            cpu: "200m"
            memory: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - sleep
          - "3600"
      