apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    app.kubernetes.io/name: app1
spec:
  containers:
  - name: app1
    image: busybox
    resources:
      requests: 
        memory: "100Mi"
        cpu: "90m"
      limits:
        memory: "200Mi"
        cpu: "200m"
    command:
      - sleep
      - "3600"
  nodeSelector: 
    app: infra

---
apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    app.kubernetes.io/name: app2
spec:
  containers:
  - name: app2
    image: busybox
    resources:
      requests: 
        memory: "100Mi"
        cpu: "90m"
      limits:
        memory: "200Mi"
        cpu: "200m"
    command:
      - sleep
      - "3600"
  nodeSelector: 
    app: mgmt    