apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol-data0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/container_data
    server: 172.31.15.178

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mount-data0
  namespace: storages
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
    
