apiVersion: v1
kind: Pod
metadata:
  name: example_pod1
  namespace: default
  labels:
    app.kubernetes.io/name: example1
spec:
  containers:
  - name: example_pod1
    image: ubuntu:latest
    restartPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    command:
      - sleep
      - "3600"  
