apiVersion: v1
kind: Namespace
metadata:
  name: webapp 

---
apiVersion: v1
kind: Pod
metadata:
  name: villaweb
  labels: 
    app.kubernetes.io/name: villaweb
spec:
  containers:
  - name: villaweb
    image: prateekkumawat/villa:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: villaweb-svc
spec:
  selector:
    app.kubernetes.io/name: villaweb
  type: NodePort
  ports:
  - name: http
    port:  80
    targetPort: 80