apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: example1
  template:
    metadata:
      labels:
        app: example1
    spec:
      containers:
      - name: wxample1-app
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: example1-svc
spec:
  selector:
    app: example1
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
